/**:
  ros__parameters:

    # List of spring names to load. Each name must have a matching
    # entry in the 'springs' namespace below.
    spring_names:
      - tip_spring


    springs:

      tip_spring:
        link_name:    "tool0_controller" # must match a frame name in the URDF
        local_point:  [0.0, 0.0, 0.0] # attachment point in link-local frame (m)
        target:       [-0.345, -0.161,0.138 ] # target position in world frame (m)
        stiffness:    300            # N/m
        damping:      0.0              # N·s/m
        rest_length:  0.0              # m  (0 = zero-length spring)